package vn.co.taxinet.orm;

// Generated Jan 26, 2015 2:47:29 PM by Hibernate Tools 4.0.0

/**
 * AccounttransactionId generated by hbm2java
 */
public class AccounttransactionId implements java.io.Serializable {

	private String userId;
	private int dateTime;

	public AccounttransactionId() {
	}

	public AccounttransactionId(String userId, int dateTime) {
		this.userId = userId;
		this.dateTime = dateTime;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public int getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(int dateTime) {
		this.dateTime = dateTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccounttransactionId))
			return false;
		AccounttransactionId castOther = (AccounttransactionId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null && castOther.getUserId() != null && this
				.getUserId().equals(castOther.getUserId())))
				&& (this.getDateTime() == castOther.getDateTime());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + this.getDateTime();
		return result;
	}

}
