package vn.co.taxinet.orm;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CarMaker generated by hbm2java
 */
public class CarMaker implements java.io.Serializable {

	private Integer carMakerId;
	private String carMaker;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;
	private Set<CarType> carTypes = new HashSet<CarType>(0);
	private Set<CarType> cartypes_1 = new HashSet<CarType>(0);

	public CarMaker() {
	}

	public CarMaker(String carMaker, String createdBy, Date createdDate,
			String lastModifiedBy, Date lastModifiedDate) {
		this.carMaker = carMaker;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	public CarMaker(String carMaker, String createdBy, Date createdDate,
			String lastModifiedBy, Date lastModifiedDate,
			Set<CarType> carTypes, Set<CarType> cartypes_1) {
		this.carMaker = carMaker;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.carTypes = carTypes;
		this.cartypes_1 = cartypes_1;
	}

	public Integer getCarMakerId() {
		return this.carMakerId;
	}

	public void setCarMakerId(Integer carMakerId) {
		this.carMakerId = carMakerId;
	}

	public String getCarMaker() {
		return this.carMaker;
	}

	public void setCarMaker(String carMaker) {
		this.carMaker = carMaker;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<CarType> getCartypes() {
		return this.carTypes;
	}

	public void setCartypes(Set<CarType> carTypes) {
		this.carTypes = carTypes;
	}

	public Set<CarType> getCartypes_1() {
		return this.cartypes_1;
	}

	public void setCartypes_1(Set<CarType> cartypes_1) {
		this.cartypes_1 = cartypes_1;
	}

}
