package vn.co.taxinet.orm;

// Generated Mar 7, 2015 10:20:43 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CarType generated by hbm2java
 */
public class CarType implements java.io.Serializable {

	private Integer carTypeId;
	private CarMaker carMaker;
	private String carTittle;
	private String level;
	private int capacity;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;
	private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);
	private Set<Vehicle> vehicles_1 = new HashSet<Vehicle>(0);

	public CarType() {
	}

	public CarType(CarMaker carMaker, String carTittle, int capacity,
			String createdBy, Date createdDate, String lastModifiedBy,
			Date lastModifiedDate) {
		this.carMaker = carMaker;
		this.carTittle = carTittle;
		this.capacity = capacity;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	public CarType(CarMaker carMaker, String carTittle, String level,
			int capacity, String createdBy, Date createdDate,
			String lastModifiedBy, Date lastModifiedDate,
			Set<Vehicle> vehicles, Set<Vehicle> vehicles_1) {
		this.carMaker = carMaker;
		this.carTittle = carTittle;
		this.level = level;
		this.capacity = capacity;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.vehicles = vehicles;
		this.vehicles_1 = vehicles_1;
	}

	public Integer getCarTypeId() {
		return this.carTypeId;
	}

	public void setCarTypeId(Integer carTypeId) {
		this.carTypeId = carTypeId;
	}

	public CarMaker getCarMaker() {
		return this.carMaker;
	}

	public void setCarMaker(CarMaker carMaker) {
		this.carMaker = carMaker;
	}

	public String getCarTtittle() {
		return this.carTittle;
	}

	public void setCarTtittle(String carTittle) {
		this.carTittle = carTittle;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public int getCapacity() {
		return this.capacity;
	}

	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<Vehicle> getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Set<Vehicle> vehicles) {
		this.vehicles = vehicles;
	}

	public Set<Vehicle> getVehicles_1() {
		return this.vehicles_1;
	}

	public void setVehicles_1(Set<Vehicle> vehicles_1) {
		this.vehicles_1 = vehicles_1;
	}

}
