package vn.co.taxinet.orm;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

/**
 * CityNameID generated by hbm2java
 */
public class CityNameID implements java.io.Serializable {

	private int cityID;
	private String languageCode;

	public CityNameID() {
	}

	public CityNameID(int cityID, String languageCode) {
		this.cityID = cityID;
		this.languageCode = languageCode;
	}

	public int getCityID() {
		return this.cityID;
	}

	public void setCityID(int cityID) {
		this.cityID = cityID;
	}

	public String getLanguageCode() {
		return this.languageCode;
	}

	public void setLanguageCode(String languageCode) {
		this.languageCode = languageCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CityNameID))
			return false;
		CityNameID castOther = (CityNameID) other;

		return (this.getCityID() == castOther.getCityID())
				&& ((this.getLanguageCode() == castOther.getLanguageCode()) || (this
						.getLanguageCode() != null
						&& castOther.getLanguageCode() != null && this
						.getLanguageCode().equals(castOther.getLanguageCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCityID();
		result = 37
				* result
				+ (getLanguageCode() == null ? 0 : this.getLanguageCode()
						.hashCode());
		return result;
	}

}
