package vn.co.taxinet.orm;

// Generated Jan 26, 2015 2:47:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private Integer companyId;
	private Document documentByOperatingLisence;
	private Document documentByBusinessRegistration;
	private Address address;
	private Company company;
	private int name;
	private String businessType;
	private Integer balance;
	private Integer vatnumber;
	private Integer mobileNo;
	private Integer serviceCharge;
	private Integer rate;
	private Integer bankNo;
	private Integer bankId;
	private Integer currentPromotionCode;
	private String createdBy;
	private Date creatDate;
	private String lastModifiedBy;
	private Date lastModifyDate;
	private Set<TaxiNetUsers> taxinetuserses = new HashSet<TaxiNetUsers>(0);
	private Set<TaxiNetUsers> taxinetuserses_1 = new HashSet<TaxiNetUsers>(0);
	private Set<Pricepanel> pricepanels = new HashSet<Pricepanel>(0);
	private Set<Company> companies = new HashSet<Company>(0);
	private Set<Pricepanel> pricepanels_1 = new HashSet<Pricepanel>(0);
	private Set<Companyparkarea> companyparkareas = new HashSet<Companyparkarea>(
			0);
	private Set<Company> companies_1 = new HashSet<Company>(0);
	private Set<Companyparkarea> companyparkareas_1 = new HashSet<Companyparkarea>(
			0);

	public Company() {
	}

	public Company(Document documentByOperatingLisence,
			Document documentByBusinessRegistration, Address address,
			Company company, int name, String businessType, String createdBy,
			Date creatDate, String lastModifiedBy, Date lastModifyDate) {
		this.documentByOperatingLisence = documentByOperatingLisence;
		this.documentByBusinessRegistration = documentByBusinessRegistration;
		this.address = address;
		this.company = company;
		this.name = name;
		this.businessType = businessType;
		this.createdBy = createdBy;
		this.creatDate = creatDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifyDate = lastModifyDate;
	}

	public Company(Document documentByOperatingLisence,
			Document documentByBusinessRegistration, Address address,
			Company company, int name, String businessType, Integer balance,
			Integer vatnumber, Integer mobileNo, Integer serviceCharge,
			Integer rate, Integer bankNo, Integer bankId,
			Integer currentPromotionCode, String createdBy, Date creatDate,
			String lastModifiedBy, Date lastModifyDate,
			Set<TaxiNetUsers> taxinetuserses,
			Set<TaxiNetUsers> taxinetuserses_1, Set<Pricepanel> pricepanels,
			Set<Company> companies, Set<Pricepanel> pricepanels_1,
			Set<Companyparkarea> companyparkareas, Set<Company> companies_1,
			Set<Companyparkarea> companyparkareas_1) {
		this.documentByOperatingLisence = documentByOperatingLisence;
		this.documentByBusinessRegistration = documentByBusinessRegistration;
		this.address = address;
		this.company = company;
		this.name = name;
		this.businessType = businessType;
		this.balance = balance;
		this.vatnumber = vatnumber;
		this.mobileNo = mobileNo;
		this.serviceCharge = serviceCharge;
		this.rate = rate;
		this.bankNo = bankNo;
		this.bankId = bankId;
		this.currentPromotionCode = currentPromotionCode;
		this.createdBy = createdBy;
		this.creatDate = creatDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifyDate = lastModifyDate;
		this.taxinetuserses = taxinetuserses;
		this.taxinetuserses_1 = taxinetuserses_1;
		this.pricepanels = pricepanels;
		this.companies = companies;
		this.pricepanels_1 = pricepanels_1;
		this.companyparkareas = companyparkareas;
		this.companies_1 = companies_1;
		this.companyparkareas_1 = companyparkareas_1;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public Document getDocumentByOperatingLisence() {
		return this.documentByOperatingLisence;
	}

	public void setDocumentByOperatingLisence(
			Document documentByOperatingLisence) {
		this.documentByOperatingLisence = documentByOperatingLisence;
	}

	public Document getDocumentByBusinessRegistration() {
		return this.documentByBusinessRegistration;
	}

	public void setDocumentByBusinessRegistration(
			Document documentByBusinessRegistration) {
		this.documentByBusinessRegistration = documentByBusinessRegistration;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public int getName() {
		return this.name;
	}

	public void setName(int name) {
		this.name = name;
	}

	public String getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	public Integer getBalance() {
		return this.balance;
	}

	public void setBalance(Integer balance) {
		this.balance = balance;
	}

	public Integer getVatnumber() {
		return this.vatnumber;
	}

	public void setVatnumber(Integer vatnumber) {
		this.vatnumber = vatnumber;
	}

	public Integer getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(Integer mobileNo) {
		this.mobileNo = mobileNo;
	}

	public Integer getServiceCharge() {
		return this.serviceCharge;
	}

	public void setServiceCharge(Integer serviceCharge) {
		this.serviceCharge = serviceCharge;
	}

	public Integer getRate() {
		return this.rate;
	}

	public void setRate(Integer rate) {
		this.rate = rate;
	}

	public Integer getBankNo() {
		return this.bankNo;
	}

	public void setBankNo(Integer bankNo) {
		this.bankNo = bankNo;
	}

	public Integer getBankId() {
		return this.bankId;
	}

	public void setBankId(Integer bankId) {
		this.bankId = bankId;
	}

	public Integer getCurrentPromotionCode() {
		return this.currentPromotionCode;
	}

	public void setCurrentPromotionCode(Integer currentPromotionCode) {
		this.currentPromotionCode = currentPromotionCode;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatDate() {
		return this.creatDate;
	}

	public void setCreatDate(Date creatDate) {
		this.creatDate = creatDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifyDate() {
		return this.lastModifyDate;
	}

	public void setLastModifyDate(Date lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	public Set<TaxiNetUsers> getTaxinetuserses() {
		return this.taxinetuserses;
	}

	public void setTaxinetuserses(Set<TaxiNetUsers> taxinetuserses) {
		this.taxinetuserses = taxinetuserses;
	}

	public Set<TaxiNetUsers> getTaxinetuserses_1() {
		return this.taxinetuserses_1;
	}

	public void setTaxinetuserses_1(Set<TaxiNetUsers> taxinetuserses_1) {
		this.taxinetuserses_1 = taxinetuserses_1;
	}

	public Set<Pricepanel> getPricepanels() {
		return this.pricepanels;
	}

	public void setPricepanels(Set<Pricepanel> pricepanels) {
		this.pricepanels = pricepanels;
	}

	public Set<Company> getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set<Company> companies) {
		this.companies = companies;
	}

	public Set<Pricepanel> getPricepanels_1() {
		return this.pricepanels_1;
	}

	public void setPricepanels_1(Set<Pricepanel> pricepanels_1) {
		this.pricepanels_1 = pricepanels_1;
	}

	public Set<Companyparkarea> getCompanyparkareas() {
		return this.companyparkareas;
	}

	public void setCompanyparkareas(Set<Companyparkarea> companyparkareas) {
		this.companyparkareas = companyparkareas;
	}

	public Set<Company> getCompanies_1() {
		return this.companies_1;
	}

	public void setCompanies_1(Set<Company> companies_1) {
		this.companies_1 = companies_1;
	}

	public Set<Companyparkarea> getCompanyparkareas_1() {
		return this.companyparkareas_1;
	}

	public void setCompanyparkareas_1(Set<Companyparkarea> companyparkareas_1) {
		this.companyparkareas_1 = companyparkareas_1;
	}

}
