package vn.co.taxinet.orm;

// Generated Jan 23, 2015 10:11:00 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Companyparkarea generated by hbm2java
 */
public class Companyparkarea implements java.io.Serializable {

	private CompanyparkareaId id;
	private Company company;
	private String name;
	private int numberOfCar;
	private String creatBy;
	private Date createdDate;
	private String lastModifyBy;
	private Date lastModifiedDate;

	public Companyparkarea() {
	}

	public Companyparkarea(CompanyparkareaId id, Company company, String name,
			int numberOfCar, String creatBy, Date createdDate,
			String lastModifyBy, Date lastModifiedDate) {
		this.id = id;
		this.company = company;
		this.name = name;
		this.numberOfCar = numberOfCar;
		this.creatBy = creatBy;
		this.createdDate = createdDate;
		this.lastModifyBy = lastModifyBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	public CompanyparkareaId getId() {
		return this.id;
	}

	public void setId(CompanyparkareaId id) {
		this.id = id;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getNumberOfCar() {
		return this.numberOfCar;
	}

	public void setNumberOfCar(int numberOfCar) {
		this.numberOfCar = numberOfCar;
	}

	public String getCreatBy() {
		return this.creatBy;
	}

	public void setCreatBy(String creatBy) {
		this.creatBy = creatBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastModifyBy() {
		return this.lastModifyBy;
	}

	public void setLastModifyBy(String lastModifyBy) {
		this.lastModifyBy = lastModifyBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
