package vn.co.taxinet.orm;

// Generated Jan 23, 2015 10:11:00 AM by Hibernate Tools 4.0.0

/**
 * Currentstatus generated by hbm2java
 */
public class Currentstatus implements java.io.Serializable {

	private String driverId;
	private Driver driver;
	private Double currentLatitude;
	private Double currentLongtitude;
	private String currentStatus;

	public Currentstatus() {
	}

	public Currentstatus(Driver driver) {
		this.driver = driver;
	}

	public Currentstatus(Driver driver, Double currentLatitude,
			Double currentLongtitude, String currentStatus) {
		this.driver = driver;
		this.currentLatitude = currentLatitude;
		this.currentLongtitude = currentLongtitude;
		this.currentStatus = currentStatus;
	}

	public String getDriverId() {
		return this.driverId;
	}

	public void setDriverId(String driverId) {
		this.driverId = driverId;
	}

	public Driver getDriver() {
		return this.driver;
	}

	public void setDriver(Driver driver) {
		this.driver = driver;
	}

	public Double getCurrentLatitude() {
		return this.currentLatitude;
	}

	public void setCurrentLatitude(Double currentLatitude) {
		this.currentLatitude = currentLatitude;
	}

	public Double getCurrentLongtitude() {
		return this.currentLongtitude;
	}

	public void setCurrentLongtitude(Double currentLongtitude) {
		this.currentLongtitude = currentLongtitude;
	}

	public String getCurrentStatus() {
		return this.currentStatus;
	}

	public void setCurrentStatus(String currentStatus) {
		this.currentStatus = currentStatus;
	}

}
