package vn.co.taxinet.orm;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Driver generated by hbm2java
 */
public class Driver implements java.io.Serializable {

	private String driverId;
	private TaxiNetUsers taxiNetUsers;
	private Document documentByDriverLisense;
	private Vehicle vehicle;
	private Address address;
	private Document documentByDriveExperience;
	private String firstName;
	private String lastName;
	private String mobileNo;
	private String invitationCode;
	private String regId;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;
	private double balance;
	private CurrentStatus currentStatus;
	private Set<Trip> trips = new HashSet<Trip>(0);
	private Set<Trip> trips_1 = new HashSet<Trip>(0);

	public Driver() {
	}

	public Driver(TaxiNetUsers taxiNetUsers, String createdBy,
			Date createdDate, String lastModifiedBy, Date lastModifiedDate) {
		this.taxiNetUsers = taxiNetUsers;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	public Driver(TaxiNetUsers taxiNetUsers, Document documentByDriverLisense,
			Vehicle vehicle, Address address,
			Document documentByDriveExperience, String firstName,
			String lastName, String mobileNo, String invitationCode,
			String regId, String createdBy, Date createdDate,
			String lastModifiedBy, Date lastModifiedDate,
			CurrentStatus currentStatus, Set<Trip> trips,
			Set<Trip> trips_1) {
		this.taxiNetUsers = taxiNetUsers;
		this.documentByDriverLisense = documentByDriverLisense;
		this.vehicle = vehicle;
		this.address = address;
		this.documentByDriveExperience = documentByDriveExperience;
		this.firstName = firstName;
		this.lastName = lastName;
		this.mobileNo = mobileNo;
		this.invitationCode = invitationCode;
		this.regId = regId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.currentStatus = currentStatus;
		this.trips = trips;
		this.currentStatus = currentStatus;
		this.trips_1 = trips_1;
	}

	public String getDriverId() {
		return this.driverId;
	}

	public void setDriverId(String driverId) {
		this.driverId = driverId;
	}

	public TaxiNetUsers getTaxinetusers() {
		return this.taxiNetUsers;
	}

	public void setTaxinetusers(TaxiNetUsers taxiNetUsers) {
		this.taxiNetUsers = taxiNetUsers;
	}

	public Document getDocumentByDriverLisense() {
		return this.documentByDriverLisense;
	}

	public void setDocumentByDriverLisense(Document documentByDriverLisense) {
		this.documentByDriverLisense = documentByDriverLisense;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Document getDocumentByDriveExperience() {
		return this.documentByDriveExperience;
	}

	public void setDocumentByDriveExperience(Document documentByDriveExperience) {
		this.documentByDriveExperience = documentByDriveExperience;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getInvitationCode() {
		return this.invitationCode;
	}

	public void setInvitationCode(String invitationCode) {
		this.invitationCode = invitationCode;
	}

	public String getRegId() {
		return this.regId;
	}

	public void setRegId(String regId) {
		this.regId = regId;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<Trip> getTrips() {
		return this.trips;
	}

	public void setTrips(Set<Trip> trips) {
		this.trips = trips;
	}

	public CurrentStatus getCurrentstatus() {
		return this.currentStatus;
	}

	public void setCurrentstatus(CurrentStatus currentStatus) {
		this.currentStatus = currentStatus;
	}

	public Set<Trip> getTrips_1() {
		return this.trips_1;
	}

	public void setTrips_1(Set<Trip> trips_1) {
		this.trips_1 = trips_1;
	}

	public double getBalance() {
		return balance;
	}

	public void setBalance(double balance) {
		this.balance = balance;
	}

}
