package vn.co.taxinet.orm;

// Generated Jan 23, 2015 10:11:00 AM by Hibernate Tools 4.0.0

/**
 * Invitationlog generated by hbm2java
 */
public class Invitationlog implements java.io.Serializable {

	private InvitationlogId id;

	public Invitationlog() {
	}

	public Invitationlog(InvitationlogId id) {
		this.id = id;
	}

	public InvitationlogId getId() {
		return this.id;
	}

	public void setId(InvitationlogId id) {
		this.id = id;
	}

}
