package vn.co.taxinet.orm;

// Generated Jan 26, 2015 2:47:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private Integer paymentId;
	private Bank bank;
	private TaxiNetUsers taxinetusers;
	private String cardNo;
	private String expiredYear;
	private String expiredMonth;
	private String cvv;
	private String type;
	private String status;
	private String createdBy;
	private Date createDate;
	private String lastModifiedBy;
	private Date lastModifyDate;
	private Set<Trip> trips = new HashSet<Trip>(0);
	private Set<Trip> trips_1 = new HashSet<Trip>(0);

	public Payment() {
	}

	public Payment(Bank bank, TaxiNetUsers taxinetusers, String cardNo) {
		this.bank = bank;
		this.taxinetusers = taxinetusers;
		this.cardNo = cardNo;
	}

	public Payment(Bank bank, TaxiNetUsers taxinetusers, String cardNo,
			String expiredYear, String expiredMonth, String cvv, String type,
			String status, String createdBy, Date createDate,
			String lastModifiedBy, Date lastModifyDate, Set<Trip> trips,
			Set<Trip> trips_1) {
		this.bank = bank;
		this.taxinetusers = taxinetusers;
		this.cardNo = cardNo;
		this.expiredYear = expiredYear;
		this.expiredMonth = expiredMonth;
		this.cvv = cvv;
		this.type = type;
		this.status = status;
		this.createdBy = createdBy;
		this.createDate = createDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifyDate = lastModifyDate;
		this.trips = trips;
		this.trips_1 = trips_1;
	}

	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	public Bank getBank() {
		return this.bank;
	}

	public void setBank(Bank bank) {
		this.bank = bank;
	}

	public TaxiNetUsers getTaxinetusers() {
		return this.taxinetusers;
	}

	public void setTaxinetusers(TaxiNetUsers taxinetusers) {
		this.taxinetusers = taxinetusers;
	}

	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	public String getExpiredYear() {
		return this.expiredYear;
	}

	public void setExpiredYear(String expiredYear) {
		this.expiredYear = expiredYear;
	}

	public String getExpiredMonth() {
		return this.expiredMonth;
	}

	public void setExpiredMonth(String expiredMonth) {
		this.expiredMonth = expiredMonth;
	}

	public String getCvv() {
		return this.cvv;
	}

	public void setCvv(String cvv) {
		this.cvv = cvv;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifyDate() {
		return this.lastModifyDate;
	}

	public void setLastModifyDate(Date lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	public Set<Trip> getTrips() {
		return this.trips;
	}

	public void setTrips(Set<Trip> trips) {
		this.trips = trips;
	}

	public Set<Trip> getTrips_1() {
		return this.trips_1;
	}

	public void setTrips_1(Set<Trip> trips_1) {
		this.trips_1 = trips_1;
	}

}
