package vn.co.taxinet.orm;

// Generated Jan 26, 2015 2:47:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pricepanel generated by hbm2java
 */
public class Pricepanel implements java.io.Serializable {
	private static final long serialVersionUID = -3736430404900935604L;
	private Integer pricePanelId;
	private Carmodel carmodel;
	private Company company;
	private Integer price;
	private Date startDate;
	private Date endDate;
	private Integer openKm;
	private Integer openPrice;
	private Integer firstKm;
	private Integer firstKmprice;
	private Integer nextKm;
	private Integer nextKmprice;
	private Integer waitingPrice;
	private String createdBy;
	private Date creatDate;
	private String lastModifiedBy;
	private Date lastModifyDate;
	private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);
	private Set<Vehicle> vehicles_1 = new HashSet<Vehicle>(0);

	public Pricepanel() {
	}

	public Pricepanel(Carmodel carmodel, Company company, Date startDate,
			String createdBy, Date creatDate, String lastModifiedBy,
			Date lastModifyDate) {
		this.carmodel = carmodel;
		this.company = company;
		this.startDate = startDate;
		this.createdBy = createdBy;
		this.creatDate = creatDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifyDate = lastModifyDate;
	}

	public Pricepanel(Carmodel carmodel, Company company, Integer price,
			Date startDate, Date endDate, Integer openKm, Integer openPrice,
			Integer firstKm, Integer firstKmprice, Integer nextKm,
			Integer nextKmprice, Integer waitingPrice, String createdBy,
			Date creatDate, String lastModifiedBy, Date lastModifyDate,
			Set<Vehicle> vehicles, Set<Vehicle> vehicles_1) {
		this.carmodel = carmodel;
		this.company = company;
		this.price = price;
		this.startDate = startDate;
		this.endDate = endDate;
		this.openKm = openKm;
		this.openPrice = openPrice;
		this.firstKm = firstKm;
		this.firstKmprice = firstKmprice;
		this.nextKm = nextKm;
		this.nextKmprice = nextKmprice;
		this.waitingPrice = waitingPrice;
		this.createdBy = createdBy;
		this.creatDate = creatDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifyDate = lastModifyDate;
		this.vehicles = vehicles;
		this.vehicles_1 = vehicles_1;
	}

	public Integer getPricePanelId() {
		return this.pricePanelId;
	}

	public void setPricePanelId(Integer pricePanelId) {
		this.pricePanelId = pricePanelId;
	}

	public Carmodel getCarmodel() {
		return this.carmodel;
	}

	public void setCarmodel(Carmodel carmodel) {
		this.carmodel = carmodel;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getOpenKm() {
		return this.openKm;
	}

	public void setOpenKm(Integer openKm) {
		this.openKm = openKm;
	}

	public Integer getOpenPrice() {
		return this.openPrice;
	}

	public void setOpenPrice(Integer openPrice) {
		this.openPrice = openPrice;
	}

	public Integer getFirstKm() {
		return this.firstKm;
	}

	public void setFirstKm(Integer firstKm) {
		this.firstKm = firstKm;
	}

	public Integer getFirstKmprice() {
		return this.firstKmprice;
	}

	public void setFirstKmprice(Integer firstKmprice) {
		this.firstKmprice = firstKmprice;
	}

	public Integer getNextKm() {
		return this.nextKm;
	}

	public void setNextKm(Integer nextKm) {
		this.nextKm = nextKm;
	}

	public Integer getNextKmprice() {
		return this.nextKmprice;
	}

	public void setNextKmprice(Integer nextKmprice) {
		this.nextKmprice = nextKmprice;
	}

	public Integer getWaitingPrice() {
		return this.waitingPrice;
	}

	public void setWaitingPrice(Integer waitingPrice) {
		this.waitingPrice = waitingPrice;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatDate() {
		return this.creatDate;
	}

	public void setCreatDate(Date creatDate) {
		this.creatDate = creatDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifyDate() {
		return this.lastModifyDate;
	}

	public void setLastModifyDate(Date lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	public Set<Vehicle> getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Set<Vehicle> vehicles) {
		this.vehicles = vehicles;
	}

	public Set<Vehicle> getVehicles_1() {
		return this.vehicles_1;
	}

	public void setVehicles_1(Set<Vehicle> vehicles_1) {
		this.vehicles_1 = vehicles_1;
	}

}
