package vn.co.taxinet.orm;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle implements java.io.Serializable {

	private Integer vehicleId;
	private PricePanel pricePanel;
	private String plate;
	private String interiorColor;
	private String exteriorColor;
	private String produceYear;
	private Integer lisencePlatCountry;
	private Integer lisencePlatState;
	private String createdBy;
	private Date creatDate;
	private String lastModifiedBy;
	private Date lastModifyDate;
	private Set<Driver> drivers = new HashSet<Driver>(0);
	private Set<Driver> drivers_1 = new HashSet<Driver>(0);
	private Set<Trip> trips = new HashSet<Trip>(0);
	private Set<Trip> trips_1 = new HashSet<Trip>(0);

	public Vehicle() {
	}

	public Vehicle(PricePanel pricePanel, String plate, String createdBy,
			Date creatDate, String lastModifiedBy, Date lastModifyDate) {
		this.pricePanel = pricePanel;
		this.plate = plate;
		this.createdBy = createdBy;
		this.creatDate = creatDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifyDate = lastModifyDate;
	}

	public Vehicle(PricePanel pricePanel, String plate, String interiorColor,
			String exteriorColor, String produceYear,
			Integer lisencePlatCountry, Integer lisencePlatState,
			String createdBy, Date creatDate, String lastModifiedBy,
			Date lastModifyDate, Set<Driver> drivers, Set<Driver> drivers_1,
			Set<Trip> trips, Set<Trip> trips_1) {
		this.pricePanel = pricePanel;
		this.plate = plate;
		this.interiorColor = interiorColor;
		this.exteriorColor = exteriorColor;
		this.produceYear = produceYear;
		this.lisencePlatCountry = lisencePlatCountry;
		this.lisencePlatState = lisencePlatState;
		this.createdBy = createdBy;
		this.creatDate = creatDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifyDate = lastModifyDate;
		this.drivers = drivers;
		this.drivers_1 = drivers_1;
		this.trips = trips;
		this.trips_1 = trips_1;
	}

	public Integer getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Integer vehicleId) {
		this.vehicleId = vehicleId;
	}

	public PricePanel getPricepanel() {
		return this.pricePanel;
	}

	public void setPricepanel(PricePanel pricePanel) {
		this.pricePanel = pricePanel;
	}

	public String getPlate() {
		return this.plate;
	}

	public void setPlate(String plate) {
		this.plate = plate;
	}

	public String getInteriorColor() {
		return this.interiorColor;
	}

	public void setInteriorColor(String interiorColor) {
		this.interiorColor = interiorColor;
	}

	public String getExteriorColor() {
		return this.exteriorColor;
	}

	public void setExteriorColor(String exteriorColor) {
		this.exteriorColor = exteriorColor;
	}

	public String getProduceYear() {
		return this.produceYear;
	}

	public void setProduceYear(String produceYear) {
		this.produceYear = produceYear;
	}

	public Integer getLisencePlatCountry() {
		return this.lisencePlatCountry;
	}

	public void setLisencePlatCountry(Integer lisencePlatCountry) {
		this.lisencePlatCountry = lisencePlatCountry;
	}

	public Integer getLisencePlatState() {
		return this.lisencePlatState;
	}

	public void setLisencePlatState(Integer lisencePlatState) {
		this.lisencePlatState = lisencePlatState;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatDate() {
		return this.creatDate;
	}

	public void setCreatDate(Date creatDate) {
		this.creatDate = creatDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifyDate() {
		return this.lastModifyDate;
	}

	public void setLastModifyDate(Date lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	public Set<Driver> getDrivers() {
		return this.drivers;
	}

	public void setDrivers(Set<Driver> drivers) {
		this.drivers = drivers;
	}

	public Set<Driver> getDrivers_1() {
		return this.drivers_1;
	}

	public void setDrivers_1(Set<Driver> drivers_1) {
		this.drivers_1 = drivers_1;
	}

	public Set<Trip> getTrips() {
		return this.trips;
	}

	public void setTrips(Set<Trip> trips) {
		this.trips = trips;
	}

	public Set<Trip> getTrips_1() {
		return this.trips_1;
	}

	public void setTrips_1(Set<Trip> trips_1) {
		this.trips_1 = trips_1;
	}

}
