package vn.co.taxinet.orm;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle implements java.io.Serializable {

	private Integer vehicleId;
	private Document documentByLisencePlatState;
	private Document documentByLisencePlatCountry;
	private Company company;
	private CarType carType;
	private PricePanel pricePanel;
	private String plate;
	private String interiorColor;
	private String exteriorColor;
	private String produceYear;
	private String level;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;
	private Set<Driver> drivers = new HashSet<Driver>(0);
	private Set<Trip> trips = new HashSet<Trip>(0);
	private Set<Trip> trips_1 = new HashSet<Trip>(0);

	public Vehicle() {
	}

	public Vehicle(CarType carType, String plate, String createdBy,
			Date createdDate, String lastModifiedBy, Date lastModifiedDate) {
		this.carType = carType;
		this.plate = plate;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	public Vehicle(Company company, CarType carType, PricePanel pricePanel,
			String plate, String interiorColor, String exteriorColor,
			String produceYear, Integer lisencePlatCountry,
			Integer lisencePlatState, String level, String createdBy,
			Date createdDate, String lastModifiedBy, Date lastModifiedDate, Set<Driver> drivers,
			Set<Trip> trips, Set<Trip> trips_1) {
		this.company = company;
		this.carType = carType;
		this.pricePanel = pricePanel;
		this.plate = plate;
		this.interiorColor = interiorColor;
		this.exteriorColor = exteriorColor;
		this.produceYear = produceYear;
		this.level = level;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.drivers = drivers;
		this.trips = trips;
		this.trips_1 = trips_1;
	}

	public Integer getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Integer vehicleId) {
		this.vehicleId = vehicleId;
	}

	public Document getDocumentByLisencePlatState() {
		return this.documentByLisencePlatState;
	}

	public void setDocumentByLisencePlatState(
			Document documentByLisencePlatState) {
		this.documentByLisencePlatState = documentByLisencePlatState;
	}

	public Document getDocumentByLisencePlatCountry() {
		return this.documentByLisencePlatCountry;
	}

	public void setDocumentByLisencePlatCountry(
			Document documentByLisencePlatCountry) {
		this.documentByLisencePlatCountry = documentByLisencePlatCountry;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public CarType getCartype() {
		return this.carType;
	}

	public void setCartype(CarType carType) {
		this.carType = carType;
	}

	public PricePanel getPricepanel() {
		return this.pricePanel;
	}

	public void setPricepanel(PricePanel pricePanel) {
		this.pricePanel = pricePanel;
	}

	public String getPlate() {
		return this.plate;
	}

	public void setPlate(String plate) {
		this.plate = plate;
	}

	public String getInteriorColor() {
		return this.interiorColor;
	}

	public void setInteriorColor(String interiorColor) {
		this.interiorColor = interiorColor;
	}

	public String getExteriorColor() {
		return this.exteriorColor;
	}

	public void setExteriorColor(String exteriorColor) {
		this.exteriorColor = exteriorColor;
	}

	public String getProduceYear() {
		return this.produceYear;
	}

	public void setProduceYear(String produceYear) {
		this.produceYear = produceYear;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<Driver> getDrivers() {
		return this.drivers;
	}

	public void setDrivers(Set<Driver> drivers) {
		this.drivers = drivers;
	}

	public Set<Trip> getTrips() {
		return this.trips;
	}

	public void setTrips(Set<Trip> trips) {
		this.trips = trips;
	}

	public Set<Trip> getTrips_1() {
		return this.trips_1;
	}

	public void setTrips_1(Set<Trip> trips_1) {
		this.trips_1 = trips_1;
	}

}
