package vn.co.taxinet.orm;

// Generated Feb 4, 2015 10:07:46 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Agent generated by hbm2java
 */
public class Agent implements java.io.Serializable {

	private String agentId;
	private Address addressByHomeAddressId;
	private TaxiNetUsers taxinetusers;
	private Address addressByOfficeAddressId;
	private String firstName;
	private String lastName;
	private String mobileNo;
	private String vatnumber;
	private String promotionCode;
	private String parentId;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;

	public Agent() {
	}

	public Agent(TaxiNetUsers taxinetusers, String firstName, String lastName,
			String mobileNo, String createdBy, Date createdDate,
			String lastModifiedBy, Date lastModifiedDate) {
		this.taxinetusers = taxinetusers;
		this.firstName = firstName;
		this.lastName = lastName;
		this.mobileNo = mobileNo;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	public Agent(Address addressByHomeAddressId, TaxiNetUsers taxinetusers,
			Address addressByOfficeAddressId, String firstName,
			String lastName, String mobileNo, String vatnumber,
			String promotionCode, String parentId, String createdBy,
			Date createdDate, String lastModifiedBy, Date lastModifiedDate) {
		this.addressByHomeAddressId = addressByHomeAddressId;
		this.taxinetusers = taxinetusers;
		this.addressByOfficeAddressId = addressByOfficeAddressId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.mobileNo = mobileNo;
		this.vatnumber = vatnumber;
		this.promotionCode = promotionCode;
		this.parentId = parentId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	public String getAgentId() {
		return this.agentId;
	}

	public void setAgentId(String agentId) {
		this.agentId = agentId;
	}

	public Address getAddressByHomeAddressId() {
		return this.addressByHomeAddressId;
	}

	public void setAddressByHomeAddressId(Address addressByHomeAddressId) {
		this.addressByHomeAddressId = addressByHomeAddressId;
	}
	
	public TaxiNetUsers getTaxinetusers() {
		return taxinetusers;
	}

	public void setTaxinetusers(TaxiNetUsers taxinetusers) {
		this.taxinetusers = taxinetusers;
	}
	
	public Address getAddressByOfficeAddressId() {
		return this.addressByOfficeAddressId;
	}

	public void setAddressByOfficeAddressId(Address addressByOfficeAddressId) {
		this.addressByOfficeAddressId = addressByOfficeAddressId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getVatnumber() {
		return this.vatnumber;
	}

	public void setVatnumber(String vatnumber) {
		this.vatnumber = vatnumber;
	}

	public String getPromotionCode() {
		return this.promotionCode;
	}

	public void setPromotionCode(String promotionCode) {
		this.promotionCode = promotionCode;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
