package vn.co.taxinet.orm;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CarMaker generated by hbm2java
 */
public class CarMaker implements java.io.Serializable {

	private Integer carMakerId;
	private String carMaker;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;
	private Set<CarModel> carModels = new HashSet<CarModel>(0);
	private Set<CarModel> carmodels_1 = new HashSet<CarModel>(0);

	public CarMaker() {
	}

	public CarMaker(String carMaker, String createdBy, Date createdDate,
			String lastModifiedBy, Date lastModifiedDate) {
		this.carMaker = carMaker;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	public CarMaker(String carMaker, String createdBy, Date createdDate,
			String lastModifiedBy, Date lastModifiedDate,
			Set<CarModel> carModels, Set<CarModel> carmodels_1) {
		this.carMaker = carMaker;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.carModels = carModels;
		this.carmodels_1 = carmodels_1;
	}

	public Integer getCarMakerId() {
		return this.carMakerId;
	}

	public void setCarMakerId(Integer carMakerId) {
		this.carMakerId = carMakerId;
	}

	public String getCarMaker() {
		return this.carMaker;
	}

	public void setCarMaker(String carMaker) {
		this.carMaker = carMaker;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<CarModel> getCarmodels() {
		return this.carModels;
	}

	public void setCarmodels(Set<CarModel> carModels) {
		this.carModels = carModels;
	}

	public Set<CarModel> getCarmodels_1() {
		return this.carmodels_1;
	}

	public void setCarmodels_1(Set<CarModel> carmodels_1) {
		this.carmodels_1 = carmodels_1;
	}

}
