package vn.co.taxinet.orm;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

/**
 * InvitationLogID generated by hbm2java
 */
public class InvitationLogID implements java.io.Serializable {

	private Integer driverId;
	private Integer riderId;

	public InvitationLogID() {
	}

	public InvitationLogID(Integer driverId, Integer riderId) {
		this.driverId = driverId;
		this.riderId = riderId;
	}

	public Integer getDriverId() {
		return this.driverId;
	}

	public void setDriverId(Integer driverId) {
		this.driverId = driverId;
	}

	public Integer getRiderId() {
		return this.riderId;
	}

	public void setRiderId(Integer riderId) {
		this.riderId = riderId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvitationLogID))
			return false;
		InvitationLogID castOther = (InvitationLogID) other;

		return ((this.getDriverId() == castOther.getDriverId()) || (this
				.getDriverId() != null && castOther.getDriverId() != null && this
				.getDriverId().equals(castOther.getDriverId())))
				&& ((this.getRiderId() == castOther.getRiderId()) || (this
						.getRiderId() != null && castOther.getRiderId() != null && this
						.getRiderId().equals(castOther.getRiderId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDriverId() == null ? 0 : this.getDriverId().hashCode());
		result = 37 * result
				+ (getRiderId() == null ? 0 : this.getRiderId().hashCode());
		return result;
	}

}
