package vn.co.taxinet.orm;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * AccountTransaction generated by hbm2java
 */
public class AccountTransaction implements java.io.Serializable {

	private Integer transactionId;
	private TaxiNetUsers taxiNetUsers;
	private int dateTime;
	private Double amount;
	private String type;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;

	public AccountTransaction() {
	}

	public AccountTransaction(TaxiNetUsers taxiNetUsers, int dateTime,
			String createdBy, Date createdDate, String lastModifiedBy,
			Date lastModifiedDate) {
		this.taxiNetUsers = taxiNetUsers;
		this.dateTime = dateTime;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	public AccountTransaction(TaxiNetUsers taxiNetUsers, int dateTime,
			Double amount, String type, String createdBy, Date createdDate,
			String lastModifiedBy, Date lastModifiedDate) {
		this.taxiNetUsers = taxiNetUsers;
		this.dateTime = dateTime;
		this.amount = amount;
		this.type = type;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	public Integer getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Integer transactionId) {
		this.transactionId = transactionId;
	}

	public TaxiNetUsers getTaxinetusers() {
		return this.taxiNetUsers;
	}

	public void setTaxinetusers(TaxiNetUsers taxiNetUsers) {
		this.taxiNetUsers = taxiNetUsers;
	}

	public int getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(int dateTime) {
		this.dateTime = dateTime;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
