package vn.co.taxinet.orm;

// Generated Jan 23, 2015 10:11:00 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Carmaker generated by hbm2java
 */
public class Carmaker implements java.io.Serializable {

	private String carMaker;
	private String createdBy;
	private Date createDate;
	private String lastModifiedBy;
	private Date lastModfyDate;
	private Set<Carmodel> carmodels = new HashSet<Carmodel>(0);
	private Set<Carmodel> carmodels_1 = new HashSet<Carmodel>(0);

	public Carmaker() {
	}

	public Carmaker(String carMaker, String createdBy, Date createDate,
			String lastModifiedBy, Date lastModfyDate) {
		this.carMaker = carMaker;
		this.createdBy = createdBy;
		this.createDate = createDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModfyDate = lastModfyDate;
	}

	public Carmaker(String carMaker, String createdBy, Date createDate,
			String lastModifiedBy, Date lastModfyDate, Set<Carmodel> carmodels,
			Set<Carmodel> carmodels_1) {
		this.carMaker = carMaker;
		this.createdBy = createdBy;
		this.createDate = createDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModfyDate = lastModfyDate;
		this.carmodels = carmodels;
		this.carmodels_1 = carmodels_1;
	}

	public String getCarMaker() {
		return this.carMaker;
	}

	public void setCarMaker(String carMaker) {
		this.carMaker = carMaker;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModfyDate() {
		return this.lastModfyDate;
	}

	public void setLastModfyDate(Date lastModfyDate) {
		this.lastModfyDate = lastModfyDate;
	}

	public Set<Carmodel> getCarmodels() {
		return this.carmodels;
	}

	public void setCarmodels(Set<Carmodel> carmodels) {
		this.carmodels = carmodels;
	}

	public Set<Carmodel> getCarmodels_1() {
		return this.carmodels_1;
	}

	public void setCarmodels_1(Set<Carmodel> carmodels_1) {
		this.carmodels_1 = carmodels_1;
	}

}
