package vn.co.taxinet.orm;

// Generated Jan 26, 2015 2:47:29 PM by Hibernate Tools 4.0.0

/**
 * CompanyparkareaId generated by hbm2java
 */
public class CompanyparkareaId implements java.io.Serializable {

	private int companyId;
	private double latitute;
	private double longtitude;

	public CompanyparkareaId() {
	}

	public CompanyparkareaId(int companyId, double latitute, double longtitude) {
		this.companyId = companyId;
		this.latitute = latitute;
		this.longtitude = longtitude;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public double getLatitute() {
		return this.latitute;
	}

	public void setLatitute(double latitute) {
		this.latitute = latitute;
	}

	public double getLongtitude() {
		return this.longtitude;
	}

	public void setLongtitude(double longtitude) {
		this.longtitude = longtitude;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CompanyparkareaId))
			return false;
		CompanyparkareaId castOther = (CompanyparkareaId) other;

		return (this.getCompanyId() == castOther.getCompanyId())
				&& (this.getLatitute() == castOther.getLatitute())
				&& (this.getLongtitude() == castOther.getLongtitude());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCompanyId();
		result = 37 * result + (int) this.getLatitute();
		result = 37 * result + (int) this.getLongtitude();
		return result;
	}

}
