package vn.co.taxinet.orm;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

/**
 * FavoriteDriverID generated by hbm2java
 */
public class FavoriteDriverID implements java.io.Serializable {

	private int riderID;
	private int driverID;

	public FavoriteDriverID() {
	}

	public FavoriteDriverID(int riderID, int driverID) {
		this.riderID = riderID;
		this.driverID = driverID;
	}

	public int getRiderID() {
		return this.riderID;
	}

	public void setRiderID(int riderID) {
		this.riderID = riderID;
	}

	public int getDriverID() {
		return this.driverID;
	}

	public void setDriverID(int driverID) {
		this.driverID = driverID;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoriteDriverID))
			return false;
		FavoriteDriverID castOther = (FavoriteDriverID) other;

		return (this.getRiderID() == castOther.getRiderID())
				&& (this.getDriverID() == castOther.getDriverID());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRiderID();
		result = 37 * result + this.getDriverID();
		return result;
	}

}
