package vn.co.taxinet.orm;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

/**
 * InvitationLogID generated by hbm2java
 */
public class InvitationLogID implements java.io.Serializable {

	private Integer driverID;
	private Integer riderID;

	public InvitationLogID() {
	}

	public InvitationLogID(Integer driverID, Integer riderID) {
		this.driverID = driverID;
		this.riderID = riderID;
	}

	public Integer getDriverID() {
		return this.driverID;
	}

	public void setDriverID(Integer driverID) {
		this.driverID = driverID;
	}

	public Integer getRiderID() {
		return this.riderID;
	}

	public void setRiderID(Integer riderID) {
		this.riderID = riderID;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvitationLogID))
			return false;
		InvitationLogID castOther = (InvitationLogID) other;

		return ((this.getDriverID() == castOther.getDriverID()) || (this
				.getDriverID() != null && castOther.getDriverID() != null && this
				.getDriverID().equals(castOther.getDriverID())))
				&& ((this.getRiderID() == castOther.getRiderID()) || (this
						.getRiderID() != null && castOther.getRiderID() != null && this
						.getRiderID().equals(castOther.getRiderID())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDriverID() == null ? 0 : this.getDriverID().hashCode());
		result = 37 * result
				+ (getRiderID() == null ? 0 : this.getRiderID().hashCode());
		return result;
	}

}
