package vn.co.taxinet.orm;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

/**
 * InvitationLog generated by hbm2java
 */
public class InvitationLog implements java.io.Serializable {

	private InvitationLogID id;

	public InvitationLog() {
	}

	public InvitationLog(InvitationLogID id) {
		this.id = id;
	}

	public InvitationLogID getID() {
		return this.id;
	}

	public void setID(InvitationLogID id) {
		this.id = id;
	}

}
