package vn.co.taxinet.orm;

// Generated Jan 26, 2015 2:47:29 PM by Hibernate Tools 4.0.0

/**
 * Invitationlog generated by hbm2java
 */
public class Invitationlog implements java.io.Serializable {
	private static final long serialVersionUID = 1381411514878504240L;
	private InvitationlogId id;

	public Invitationlog() {
	}

	public Invitationlog(InvitationlogId id) {
		this.id = id;
	}

	public InvitationlogId getId() {
		return this.id;
	}

	public void setId(InvitationlogId id) {
		this.id = id;
	}

}
