package vn.co.taxinet.orm;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PricePanel generated by hbm2java
 */
public class PricePanel implements java.io.Serializable {

	private Integer pricePanelID;
	private CarModel carModel;
	private Company company;
	private Integer price;
	private Date startDate;
	private Date endDate;
	private Integer openKm;
	private Double openPrice;
	private Integer firstKm;
	private Double firstKmprice;
	private Integer nextKm;
	private Double nextKmprice;
	private Double waitingPrice;
	private Double returnTripPrice;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;
	private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);
	private Set<Vehicle> vehicles_1 = new HashSet<Vehicle>(0);

	public PricePanel() {
	}

	public PricePanel(CarModel carModel, Company company, Date startDate,
			String createdBy, Date createdDate, String lastModifiedBy,
			Date lastModifiedDate) {
		this.carModel = carModel;
		this.company = company;
		this.startDate = startDate;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	public PricePanel(CarModel carModel, Company company, Integer price,
			Date startDate, Date endDate, Integer openKm, Double openPrice,
			Integer firstKm, Double firstKmprice, Integer nextKm,
			Double nextKmprice, Double waitingPrice, Double returnTripPrice,
			String createdBy, Date createdDate, String lastModifiedBy,
 			Date lastModifiedDate, Set<Vehicle> vehicles,
			Set<Vehicle> vehicles_1) {
		this.carModel = carModel;
		this.company = company;
		this.price = price;
		this.startDate = startDate;
		this.endDate = endDate;
		this.openKm = openKm;
		this.openPrice = openPrice;
		this.firstKm = firstKm;
		this.firstKmprice = firstKmprice;
		this.nextKm = nextKm;
		this.nextKmprice = nextKmprice;
		this.waitingPrice = waitingPrice;
		this.returnTripPrice = returnTripPrice;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.vehicles = vehicles;
		this.vehicles_1 = vehicles_1;
	}

	public Integer getPricePanelID() {
		return this.pricePanelID;
	}

	public void setPricePanelID(Integer pricePanelID) {
		this.pricePanelID = pricePanelID;
	}

	public CarModel getCarmodel() {
		return this.carModel;
	}

	public void setCarmodel(CarModel carModel) {
		this.carModel = carModel;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getOpenKm() {
		return this.openKm;
	}

	public void setOpenKm(Integer openKm) {
		this.openKm = openKm;
	}

	public Double getOpenPrice() {
		return this.openPrice;
	}

	public void setOpenPrice(Double openPrice) {
		this.openPrice = openPrice;
	}

	public Integer getFirstKm() {
		return this.firstKm;
	}

	public void setFirstKm(Integer firstKm) {
		this.firstKm = firstKm;
	}

	public Double getFirstKmprice() {
		return this.firstKmprice;
	}

	public void setFirstKmprice(Double firstKmprice) {
		this.firstKmprice = firstKmprice;
	}

	public Integer getNextKm() {
		return this.nextKm;
	}

	public void setNextKm(Integer nextKm) {
		this.nextKm = nextKm;
	}

	public Double getNextKmprice() {
		return this.nextKmprice;
	}

	public void setNextKmprice(Double nextKmprice) {
		this.nextKmprice = nextKmprice;
	}

	public Double getWaitingPrice() {
		return this.waitingPrice;
	}

	public void setWaitingPrice(Double waitingPrice) {
		this.waitingPrice = waitingPrice;
	}

	public Double getReturnTripPrice() {
		return this.returnTripPrice;
	}

	public void setReturnTripPrice(Double returnTripPrice) {
		this.returnTripPrice = returnTripPrice;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<Vehicle> getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Set<Vehicle> vehicles) {
		this.vehicles = vehicles;
	}

	public Set<Vehicle> getVehicles_1() {
		return this.vehicles_1;
	}

	public void setVehicles_1(Set<Vehicle> vehicles_1) {
		this.vehicles_1 = vehicles_1;
	}

}
