package vn.co.taxinet.orm;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

/**
 * ReferenceDataID generated by hbm2java
 */
public class ReferenceDataID implements java.io.Serializable {

	private String groupCode;
	private String code;
	private String languageCode;

	public ReferenceDataID() {
	}

	public ReferenceDataID(String groupCode, String code, String languageCode) {
		this.groupCode = groupCode;
		this.code = code;
		this.languageCode = languageCode;
	}

	public String getGroupCode() {
		return this.groupCode;
	}

	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getLanguageCode() {
		return this.languageCode;
	}

	public void setLanguageCode(String languageCode) {
		this.languageCode = languageCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReferenceDataID))
			return false;
		ReferenceDataID castOther = (ReferenceDataID) other;

		return ((this.getGroupCode() == castOther.getGroupCode()) || (this
				.getGroupCode() != null && castOther.getGroupCode() != null && this
				.getGroupCode().equals(castOther.getGroupCode())))
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null
						&& castOther.getCode() != null && this.getCode()
						.equals(castOther.getCode())))
				&& ((this.getLanguageCode() == castOther.getLanguageCode()) || (this
						.getLanguageCode() != null
						&& castOther.getLanguageCode() != null && this
						.getLanguageCode().equals(castOther.getLanguageCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGroupCode() == null ? 0 : this.getGroupCode().hashCode());
		result = 37 * result
				+ (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37
				* result
				+ (getLanguageCode() == null ? 0 : this.getLanguageCode()
						.hashCode());
		return result;
	}

}
