package vn.co.taxinet.orm;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rider generated by hbm2java
 */
public class Rider implements java.io.Serializable {

	private String riderID;
	private Address addressByHomeAddressID;
	private TaxiNetUsers taxiNetUsers;
	private Address addressByOfficeAddressID;
	private String firstName;
	private String lastName;
	private Integer mobileNo;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;
	private Set<Trip> trips = new HashSet<Trip>(0);
	private Set<Trip> trips_1 = new HashSet<Trip>(0);

	public Rider() {
	}

	public Rider(Address addressByHomeAddressID, TaxiNetUsers taxiNetUsers,
			Address addressByOfficeAddressID, String createdBy,
			Date createdDate, String lastModifiedBy, Date lastModifiedDate) {
		this.addressByHomeAddressID = addressByHomeAddressID;
		this.taxiNetUsers = taxiNetUsers;
		this.addressByOfficeAddressID = addressByOfficeAddressID;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	public Rider(Address addressByHomeAddressID, TaxiNetUsers taxiNetUsers,
			Address addressByOfficeAddressID, String firstName,
			String lastName, Integer mobileNo, String createdBy,
			Date createdDate, String lastModifiedBy, Date lastModifiedDate,
			Set<Trip> trips, Set<Trip> trips_1) {
		this.addressByHomeAddressID = addressByHomeAddressID;
		this.taxiNetUsers = taxiNetUsers;
		this.addressByOfficeAddressID = addressByOfficeAddressID;
		this.firstName = firstName;
		this.lastName = lastName;
		this.mobileNo = mobileNo;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.trips = trips;
		this.trips_1 = trips_1;
	}

	public String getRiderID() {
		return this.riderID;
	}

	public void setRiderID(String riderID) {
		this.riderID = riderID;
	}

	public Address getAddressByHomeAddressID() {
		return this.addressByHomeAddressID;
	}

	public void setAddressByHomeAddressID(Address addressByHomeAddressID) {
		this.addressByHomeAddressID = addressByHomeAddressID;
	}

	public TaxiNetUsers getTaxinetusers() {
		return this.taxiNetUsers;
	}

	public void setTaxinetusers(TaxiNetUsers taxiNetUsers) {
		this.taxiNetUsers = taxiNetUsers;
	}

	public Address getAddressByOfficeAddressID() {
		return this.addressByOfficeAddressID;
	}

	public void setAddressByOfficeAddressID(Address addressByOfficeAddressID) {
		this.addressByOfficeAddressID = addressByOfficeAddressID;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Integer getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(Integer mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Set<Trip> getTrips() {
		return this.trips;
	}

	public void setTrips(Set<Trip> trips) {
		this.trips = trips;
	}

	public Set<Trip> getTrips_1() {
		return this.trips_1;
	}

	public void setTrips_1(Set<Trip> trips_1) {
		this.trips_1 = trips_1;
	}

}
