package vn.co.taxinet.orm;

// Generated Mar 7, 2015 10:20:43 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Staff generated by hbm2java
 */
public class Staff implements java.io.Serializable {

	private String staffId;
	private BussinessUnit bussinessUnit;
	private Address address;
	private TaxiNetUsers taxiNetUsers;
	private String firstName;
	private String lastName;
	private Date dateOfBirth;
	private String nationalIdentification;
	private String mobileNo;
	private String status;
	private Date startDate;
	private Date endDate;
	private String createdBy;
	private Date createdDate;
	private String lastModifiedBy;
	private Date lastModifiedDate;

	public Staff() {
	}

	public Staff(BussinessUnit bussinessUnit, TaxiNetUsers taxiNetUsers,
			String firstName, String lastName, String createdBy,
			Date createdDate, String lastModifiedBy, Date lastModifiedDate) {
		this.bussinessUnit = bussinessUnit;
		this.taxiNetUsers = taxiNetUsers;
		this.firstName = firstName;
		this.lastName = lastName;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	public Staff(BussinessUnit bussinessUnit, Address address,
			TaxiNetUsers taxiNetUsers, String firstName, String lastName,
			Date dateOfBirth, String nationalIdentification, String mobileNo,
			String status, Date startDate, Date endDate, String createdBy,
			Date createdDate, String lastModifiedBy, Date lastModifiedDate) {
		this.bussinessUnit = bussinessUnit;
		this.address = address;
		this.taxiNetUsers = taxiNetUsers;
		this.firstName = firstName;
		this.lastName = lastName;
		this.dateOfBirth = dateOfBirth;
		this.nationalIdentification = nationalIdentification;
		this.mobileNo = mobileNo;
		this.status = status;
		this.startDate = startDate;
		this.endDate = endDate;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	public BussinessUnit getBussinessUnit() {
		return this.bussinessUnit;
	}

	public void setBussinessUnit(BussinessUnit bussinessUnit) {
		this.bussinessUnit = bussinessUnit;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public TaxiNetUsers getTaxiNetUsers() {
		return this.taxiNetUsers;
	}

	public void setTaxiNetUsers(TaxiNetUsers taxiNetUsers) {
		this.taxiNetUsers = taxiNetUsers;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getNationalIdentification() {
		return this.nationalIdentification;
	}

	public void setNationalIdentification(String nationalIdentification) {
		this.nationalIdentification = nationalIdentification;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
