package vn.co.taxinet.orm;

// Generated Jan 26, 2015 2:47:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TaxiNetUsers generated by hbm2java
 */
public class TaxiNetUsers implements java.io.Serializable {

	private String userId;
	private Usergroup usergroup;
	private Language language;
	private Company company;
	private Country country;
	private String username;
	private String password;
	private String email;
	private Integer cityId;
	private String status;
	private String image;
	private Integer postalCode;
	private Date deactivatedDate;
	private String createdBy;
	private Date creatDate;
	private String lastModifiedBy;
	private Date lastModifyDate;
	private Set<Payment> payments = new HashSet<Payment>(0);
	private Set<Payment> payments_1 = new HashSet<Payment>(0);
	private Set<Accounttransaction> accounttransactions = new HashSet<Accounttransaction>(
			0);
	private Driver driver;
	private Rider rider;
	private Set<Accounttransaction> accounttransactions_1 = new HashSet<Accounttransaction>(
			0);

	public TaxiNetUsers() {
	}

	public TaxiNetUsers(String userId, Usergroup usergroup, Language language,
			Company company, Country country, String username, String status,
			String createdBy, Date creatDate, String lastModifiedBy,
			Date lastModifyDate) {
		this.userId = userId;
		this.usergroup = usergroup;
		this.language = language;
		this.company = company;
		this.country = country;
		this.username = username;
		this.status = status;
		this.createdBy = createdBy;
		this.creatDate = creatDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifyDate = lastModifyDate;
	}

	public TaxiNetUsers(String userId, Usergroup usergroup, Language language,
			Company company, Country country, String username, String password,
			String email, Integer cityId, String status, String image,
			Integer postalCode, Date deactivatedDate, String createdBy,
			Date creatDate, String lastModifiedBy, Date lastModifyDate,
			Set<Payment> payments, Set<Payment> payments_1,
			Set<Accounttransaction> accounttransactions, Driver driver,
			Rider rider,
			Set<Accounttransaction> accounttransactions_1) {
		this.userId = userId;
		this.usergroup = usergroup;
		this.language = language;
		this.company = company;
		this.country = country;
		this.username = username;
		this.password = password;
		this.email = email;
		this.cityId = cityId;
		this.status = status;
		this.image = image;
		this.postalCode = postalCode;
		this.deactivatedDate = deactivatedDate;
		this.createdBy = createdBy;
		this.creatDate = creatDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifyDate = lastModifyDate;
		this.payments = payments;
		this.payments_1 = payments_1;
		this.accounttransactions = accounttransactions;
		this.driver = driver;
		this.rider = rider;
		this.driver = driver;
		this.rider = rider;
		this.accounttransactions_1 = accounttransactions_1;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Usergroup getUsergroup() {
		return this.usergroup;
	}

	public void setUsergroup(Usergroup usergroup) {
		this.usergroup = usergroup;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Integer getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(Integer postalCode) {
		this.postalCode = postalCode;
	}

	public Date getDeactivatedDate() {
		return this.deactivatedDate;
	}

	public void setDeactivatedDate(Date deactivatedDate) {
		this.deactivatedDate = deactivatedDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatDate() {
		return this.creatDate;
	}

	public void setCreatDate(Date creatDate) {
		this.creatDate = creatDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifyDate() {
		return this.lastModifyDate;
	}

	public void setLastModifyDate(Date lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

	public Set<Payment> getPayments_1() {
		return this.payments_1;
	}

	public void setPayments_1(Set<Payment> payments_1) {
		this.payments_1 = payments_1;
	}

	public Set<Accounttransaction> getAccounttransactions() {
		return this.accounttransactions;
	}

	public void setAccounttransactions(
			Set<Accounttransaction> accounttransactions) {
		this.accounttransactions = accounttransactions;
	}

	public Driver getDriver() {
		return this.driver;
	}

	public void setDriver(Driver driver) {
		this.driver = driver;
	}

	public Rider getRider() {
		return this.rider;
	}

	public void setRider(Rider rider) {
		this.rider = rider;
	}

	public Set<Accounttransaction> getAccounttransactions_1() {
		return this.accounttransactions_1;
	}

	public void setAccounttransactions_1(
			Set<Accounttransaction> accounttransactions_1) {
		this.accounttransactions_1 = accounttransactions_1;
	}

}
